import os 
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker, create_async_engine

"""
set the database url to an environment variable so that it can be easily changed
without modifying the code and if it is not set, it can fall back on the default
value for dev purposes.
"""
DATABASE_URL = os.environ.get(
    "DATABASE_URL",
    #you put your own database url here with your password
    #EX: postgresql+asyncpg://<yourusername>:<yourpassword>@localhost:5432/robopulse_dev_2478
    "postgresql+asyncpg://postgres:123456@localhost:5432/cashcow_dev",
)

#echo=True enables the logging of all SQL statements generated by SQLAlchemy
engine = create_async_engine(DATABASE_URL, echo=True)

#expire_on_commit=False prevents the session from expiring objects after a commit
AsyncSessionLocal = async_sessionmaker(engine, expire_on_commit=False)